name: frontend

services:
  angular:
    build:
      context: ./transcendence_front_end
      dockerfile: ../docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./transcendence_front_end:/app
      # - node_modules:/app/node_modules
      # to avoid permission issues
      # effectively excluding the .angular folder
      # from mount
      - angular_cache:/app/.angular
    ports:
      - 127.0.0.1:4200:4200

volumes:
  node_modules:
  angular_cache: