name: frontend

services:
  angular_nginx:
    container_name: angular_nginx
    depends_on:
      - angular
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    secrets:
      - ssl_cert
      - ssl_key
    networks:
    - frontend
    expose:
      - "443"
    ports:
      - "4010:443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/nginx_status"]
      interval: 30s
      start_period: 40s
      timeout: 5s
      retries: 3

  angular:
    container_name: angular
    restart: unless-stopped
    build:
      context: ./angular
      dockerfile: Dockerfile
    networks:
    - frontend
    expose:
      - "4200"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://angular:4200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  frontend:
    driver: bridge
