name: frontend

services:

  angular_nginx:
    depends_on:
      - angular
    build:
      context: nginx
      dockerfile: Dockerfile
    secrets:
      - ssl_cert
      - ssl_key
    networks:
    - frontend
    expose:
      - "443"
    ports:
      - "4010:443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/nginx_status"]
      interval: 30s
      start_period: 40s
      timeout: 5s
      retries: 3

  angular:
    networks:
    - frontend
    build:
      context: ./transcendence_front_end
      dockerfile: ../docker/Dockerfile
    restart: unless-stopped
    # volumes:
    #   - ./transcendence_front_end:/app
    #   - angular_cache:/app/.angular
    expose:
      - 4200
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://angular:4200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s



volumes:
  node_modules:
  angular_cache:

networks:
  frontend:
    driver: bridge
