# Generated by Django 5.0.6 on 2024-06-14 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(help_text='Required. 50 or fewer characters.                                     Only alphanumeric characters and -', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and -', regex='^[a-zA-Z0-9-]+$'), django.core.validators.MinLengthValidator(8, message='Nickname must be at least 8 characters long.')], verbose_name='nickname')),
                ('avatar', models.ImageField(blank=True, default='default.png', max_length=200, null=True, upload_to='', verbose_name='avatar')),
                ('intra_avatar', models.URLField(blank=True, null=True, verbose_name='intra_avatar')),
                ('online_status', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('IA', 'Inactive'), ('GA', 'Playing')], default='OF', help_text='Text describing the current user activity', max_length=2, verbose_name='online status')),
            ],
        ),
    ]
