name: backend

services:
  api_nginx:
    container_name: api_nginx
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    secrets:
      - ssl_cert
      - ssl_key
    volumes:
      - api-avatars:/app/srcs/avatars
    networks:
    - backend
    expose:
      - "443"
    ports:
      - "6010:443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/nginx_status"]
      interval: 30s
      start_period: 40s
      timeout: 5s
      retries: 3
        
  api:
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      #- ./django/srcs:/app
      - api-avatars:/app/srcs/avatars
    env_file:
    - ../.env
    networks:
    - backend
    expose:
      - 8000
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; exit(0) if requests.get(\"http://localhost:8000/api/v1/healthcheck/\").ok else exit(1)'"]
      interval: 30s
      start_period: 40s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/db
    env_file:
      - ../.env
    networks:
    - backend
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", -U, "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db-data:
  api-avatars:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./django/srcs/avatars

networks:
  backend:
    driver: bridge
