# Generated by Django 5.0.6 on 2024-09-04 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(help_text='Required. 50 or fewer characters.                                     Only alphanumeric characters and -', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and -', regex='^[a-zA-Z0-9-]+$'), django.core.validators.MinLengthValidator(5, message='Nickname must be at least 5 characters long.')], verbose_name='nickname')),
                ('avatar', models.ImageField(blank=True, default='default.png', max_length=200, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('intra_avatar', models.URLField(blank=True, null=True, verbose_name='intra_avatar')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('de', 'German'), ('pk', 'Urdu')], default='en', max_length=2)),
            ],
        ),
    ]
