name: pgadmin

services:
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4:8.6
    volumes:
      - data_volume:/var/lib/pgadmin
      - ./config:/etc/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    env_file:
      - ./.env

volumes:
  data_volume:
