# Generated by Django 5.0.6 on 2024-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_intra_user',
            field=models.BooleanField(default=False, help_text='Was user registered via 42 Intra?', verbose_name='is intra user'),
        ),
    ]
